# Generated by Django 5.1.8 on 2025-04-19 17:21

import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Book Title")),
                ("author", models.CharField(max_length=255, verbose_name="Author")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Cover"
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                (
                    "genres",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Книги Sejong", "Книги Sejong"),
                            ("Книги Topik", "Книги Topik"),
                            ("Художественная литература", "Художественная литература"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of publication"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "elibrary",
            },
        ),
    ]
