# Generated by Django 5.1.8 on 2025-05-01 05:12

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_id",
            field=models.CharField(
                blank=True, help_text="Don't touch!!!", max_length=250, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="file_id",
            field=models.CharField(
                blank=True, help_text="Don't touch!!!", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="SejongApp/book/covers",
                verbose_name="Cover",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="SejongApp/book/files",
            ),
        ),
    ]
