# Generated by Django 5.1.8 on 2025-04-19 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ManyToManyField(
                blank=True, related_name="user_set", to="users.groups"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with '+992' and be followed by exactly 9 digits.",
                        regex="^\\+992\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterModelTable(
            name="groups",
            table="groups",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
