# Generated by Django 5.1.8 on 2025-05-01 05:12

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_groups_options_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groups",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_id",
            field=models.CharField(
                blank=True, help_text="Don't touch!!!", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="SejongApp/users/avatars",
            ),
        ),
    ]
