# Generated by Django 5.1.8 on 2025-04-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_group_alter_user_avatar_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groups",
            options={},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
