# Generated by Django 5.1.8 on 2025-04-18 12:03

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(help_text='Group name', max_length=50)),
                ('time', models.JSONField(blank=True, help_text='Serialized time slots', null=True)),
                ('teacher', models.CharField(help_text='Teacher name', max_length=100)),
                ('book', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], help_text='Book number (from 1 to 8)')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.IntegerField(choices=[(301, 301), (303, 303), (306, 306), (307, 307), (308, 308)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
