# Generated by Django 5.1.8 on 2025-04-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_schedule_timejson_remove_schedule_time_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.ManyToManyField(help_text='Time slots for the schedule', to='Info.timeslot'),
        ),
    ]
