# Generated by Django 5.1.8 on 2025-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_alter_timeslot_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timeJSON',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_many_to_many',
            field=models.ManyToManyField(help_text='Time slots for the schedule', to='Info.timeslot'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.JSONField(blank=True, help_text='Serialized time slots', null=True),
        ),
    ]
